version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      github-actions-all:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      gitsubmodule-all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      pip-all:
        patterns:
          - "*"

  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  #   target-branch: "develop"
