[tool.poetry]
    name        = "bell-avr-vmc-apriltag-module"
    version     = "0.1.0"
    description = "AprilTag detection module for Bell AVR"
    license     = "MIT"
    readme      = "README.md"
    homepage    = "https://github.com/bellflight/AVR-VMC-AprilTag-Module"
    authors     = ["Nathan Vaughn <nvaughn51@gmail.com>"]

[tool.poetry.dependencies]
    python             = ">=3.9,<3.12"
    loguru             = "^0.6.0"
    bell-avr-libraries = { extras = ["mqtt"], version = "^0.1.12" }
    numpy              = "^1.23.5"
    transforms3d       = "^0.4.1"

[tool.poetry.group.dev.dependencies]
    pre-commit      = "^2.21.0"
    opencv-python   = "^4.6.0.66"     # for type-hinting
    pupil-apriltags = "^1.0.4.post10" # for type-hinting

[tool.pyright]
    typeCheckingMode = "basic"
    venvPath         = "."
    venv             = ".venv"

[tool.isort]
    profile = "black"

[tool.autoflake]
    recursive = true

[tool.flake8]
    exclude = ".venv"
    # E501 is line too long
    # E203 is whitespace before ':'
    # W503 is line break before binary operator
    ignore = "E501, E203, W503"
